### ISSUE TITLE
crash latest from fdroid

### ISSUE THREAD

**Issue by nutpantz** [wbrawner/SimpleMarkdown#96]
FATAL EXCEPTION: main
Process: com.wbrawner.simplemarkdown.free, PID: 19236
java.lang.NoSuchMethodError: No static method requireNonNullElseGet(Ljava/lang/Object;Ljava/util/function/Supplier;)Ljava/lang/Object; in class Ljava/util/Objects; or its super classes (declaration of 'java.util.Objects' appears in /system/framework/core-oj.jar)
	at C1.x0.e(SourceFile:1)
	at m4.c.<init>(SourceFile:8)
	at Q2.j0.<clinit>(SourceFile:99)
	at Q2.j0.b(SourceFile:1)
	at Q2.S.e(SourceFile:153)
	at d0.a.d(SourceFile:44)
	at d0.a.e(SourceFile:9)
	at C.n.g(SourceFile:189)
	at d0.a.g(SourceFile:52)
	at V.d.a(SourceFile:227)
	at R3.a.c(SourceFile:248)
	at E.y.a(SourceFile:104)
	at D.q.g(SourceFile:390)
	at d0.a.g(SourceFile:52)
	at V.d.a(SourceFile:227)
	at e0.g.b(SourceFile:149)
	at D.K.b(SourceFile:84)
	at y0.c.g(SourceFile:105)
	at D.n.g(SourceFile:1439)
	at d0.a.g(SourceFile:52)
	at D.n.g(SourceFile:1154)
	at d0.a.g(SourceFile:52)
	at V.d.I(SourceFile:15)
	at V.o.n(SourceFile:197)
	at V.s.i(SourceFile:33)
	at V.t0.a(SourceFile:45)
	at V.m.a(SourceFile:5)
	at V.m.a(SourceFile:5)
	at V.s.j(SourceFile:7)
	at E0.B.i(SourceFile:22)
	at E0.B.g(SourceFile:120)
	at E0.w.h0(SourceFile:173)
	at R3.e.O(SourceFile:41)
	at E.z.g(SourceFile:1542)
	at D.n.g(SourceFile:1345)
	at E0.y.d(SourceFile:72)
	at G0.u.a(SourceFile:38)
	at o0.Q.h(SourceFile:1)
	at G0.A.a(SourceFile:11)
	at C.C.h(SourceFile:97)
	at G0.A.a(SourceFile:11)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at C.e.d(SourceFile:86)
	at C.w.d(SourceFile:40)
	at G0.u.a(SourceFile:38)
	at C.T.h(SourceFile:115)
	at G0.A.a(SourceFile:11)
	at C.C.h(SourceFile:97)
	at G0.A.a(SourceFile:11)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at R.Q0.g(SourceFile:949)
	at E0.y.d(SourceFile:72)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at C.t.d(SourceFile:70)
	at G0.u.a(SourceFile:38)
	at o0.Q.h(SourceFile:1)
	at G0.A.a(SourceFile:11)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at C.t.d(SourceFile:70)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at R.F0.d(SourceFile:391)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at C.t.d(SourceFile:70)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at v.n.d(SourceFile:24)
	at G0.u.a(SourceFile:38)
	at v.E.h(SourceFile:281)
	at G0.A.a(SourceFile:11)
	at o0.o.h(SourceFile:1)
	at G0.A.a(SourceFile:11)
	at C.j0.f(SourceFile:57)
	at E0.s.h(SourceFile:8)
	at G0.A.a(SourceFile:11)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at v.f.d(SourceFile:58)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:56)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.M.a(SourceFile:91)
	at E0.S.d(SourceFile:39)
	at G0.u.a(SourceFile:38)
	at D.M.a(SourceFile:608)
	at f0.s.e(SourceFile:114)
	at f0.t.a(SourceFile:52)
	at f0.u.d(SourceFile:131)
	at G0.n0.a(SourceFile:3)
	at G0.M.m0(SourceFile:131)
	at G0.G.L(SourceFile:17)
	at G0.V.c(SourceFile:3)
	at G0.V.o(SourceFile:23)
	at G0.V.l(SourceFile:65)
	at H0.z.onMeasure(SourceFile:121)
	at android.view.View.measure(View.java:23587)
	at H0.a.e(SourceFile:64)
	at H0.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6902)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6902)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6902)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6902)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6902)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:787)
	at android.view.View.measure(View.java:23587)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2860)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1657)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1545)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7824)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:953)
	at android.view.Choreographer.doCallbacks(Choreographer.java:765)
	at android.view.Choreographer.doFrame(Choreographer.java:697)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:939)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by wbrawner** [comment]
Sorry I must've missed this. Do you have any info on what steps to take to reproduce the crash? Are you still seeing it on the latest F-droid builds?

**Comment by horsemankukka** [comment]
At least for me the crash is reproduced by just launching the app from the launcher. It shows the splash screen for less than a second and then immediately exits back to the launcher. The newest version on F-Droid available for me at least is still 2024.11.0-free but I can confirm the 2024.12.0 version from Google Play has the exact same issue as well. For me the 1.0.2-free is also the last version to work. OS version is Android 9.0.5 for me, expect this may be the same issue as #98 where the problem appeared in Android 8.1.0, maybe it's about some API feature not present in older Android versions?

**Comment by horsemankukka** [comment]
Seems that the java.util.Objects.requireNonNullElseGet showing in the stack trace above is a new method added in JDK 9 when Android 8 only supports JDK 8 features (if I understood correctly). Maybe Android 9 lacks it too? It's probably in some code generated by Android Studio as I can't find it in the repo itself, so maybe it's some problem with the API target stuff?

**Comment by wbrawner** [comment]
Thanks for looking into it! I'll push out a release this month to revert back to Java 8 and see if that fixes it for you

**Comment by wbrawner** [comment]
Update: de71d7c5cf229870d01001f6397a34d895b97c48 reverts the change that (hopefully) causes this crash. I tested on an emulator running Android 7 (API 24) and was unable to reproduce the crash. I'll close this issue for now and push out a new release, but please do re-open this issue if you continue to see the crashes on 2025.1.0
